/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import pokemonelementos.Pokemon;
import pokemonelementos.PokemonAgua;
import pokemonelementos.PokemonAire;
import pokemonelementos.PokemonFuego;
import pokemonelementos.PokemonTierra;

/**
 *
 * @author NEWSHORE
 */
public class FrmConfig extends javax.swing.JFrame {
    
    private Pokemon pokemonPlayer;
    private Pokemon pokemonComput;

    /**
     * Creates new form FrmConfig
     */
    public FrmConfig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        imgPoquemon = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        btnFilth = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elegir poquemones");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        imgPoquemon.setText("xxxx");

        lblInfo.setText("<html>hola<br>asdx<html>");

        btnFilth.setText("Pelear");
        btnFilth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSeleccionar)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(imgPoquemon, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFilth, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(btnSeleccionar)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgPoquemon, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFilth)
                        .addGap(67, 67, 67))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        
        Pokemon misPokemon[] = new Pokemon[8];
        
        misPokemon[0] = new PokemonFuego("shooks","Fuego",10,"pickachu.png",90);
        misPokemon[1] = new PokemonFuego("shooks","Fuego",10,"charmandon.png",90);
        misPokemon[2] = new PokemonAgua("shooks","Fuego",10,"bolbazor.png",50);
        misPokemon[3] = new PokemonAgua("shooks","Fuego",10,"torus.png",50);
        misPokemon[4] = new PokemonTierra("shooks","Fuego",10,"roco.png",70);
        misPokemon[5] = new PokemonTierra("shooks","Fuego",10,"spin.png",70);
        misPokemon[6] = new PokemonAire("shooks","Fuego",10,"alteo.png",60);
        misPokemon[7] = new PokemonAire("shooks","Fuego",10,"bigyo.png",60);
        
        Random random = new Random();
        int idPokemonPlayer = random.nextInt(8);
        int idPokemonComput = random.nextInt(8);
        
        this.pokemonPlayer = misPokemon[idPokemonPlayer];
        this.pokemonComput = misPokemon[idPokemonComput]; 
        System.out.println();
        
        ImageIcon imagePoquemon = new ImageIcon(System.getProperty("user.dir")+"/src/statics/"+this.pokemonPlayer.getImagen());
        ImageIcon imagePoquemonRezice = new ImageIcon(imagePoquemon.getImage().getScaledInstance(imgPoquemon.getWidth(), imgPoquemon.getHeight(), Image.SCALE_DEFAULT));
        imgPoquemon.setIcon(imagePoquemonRezice);
        lblInfo.setText(
                    "<html>name: "+this.pokemonPlayer.getNombre()+
                    "<br>elemento: "+this.pokemonPlayer.getElemento()+
                    "<br>vida: "+this.pokemonPlayer.getVida()+
                    "<html>"
                );
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnFilthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilthActionPerformed
        FrmFight frmFight = new FrmFight(this.pokemonPlayer,this.pokemonComput);
        frmFight.setVisible(true);
    }//GEN-LAST:event_btnFilthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilth;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel imgPoquemon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables
}
