/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import java.awt.Image;
import javax.swing.ImageIcon;
import pokemonelementos.Pokemon;

/**
 *
 * @author NEWSHORE
 */
public class FrmFight extends javax.swing.JFrame {
    
    private Pokemon pokemonPlayer;
    private Pokemon pokemonComput;

    /**
     * Creates new form FrmFight
     * @param pokemonPlayer
     * @param pokemonComput
     */
    public FrmFight(Pokemon pokemonPlayer, Pokemon pokemonComput) {
        initComponents();
        this.pokemonPlayer=pokemonPlayer;
        this.pokemonComput=pokemonComput;
        compile();
    }
    
    private void compile(){
        lblName.setText(this.pokemonPlayer.getNombre());
        ImageIcon imagePoquemon = new ImageIcon(System.getProperty("user.dir")+"/src/statics/"+this.pokemonPlayer.getImagen());
        ImageIcon imagePoquemonRezice = new ImageIcon(imagePoquemon.getImage().getScaledInstance(imgPoquemonUser.getWidth(), imgPoquemonUser.getHeight(), Image.SCALE_DEFAULT));
        imgPoquemonUser.setIcon(imagePoquemonRezice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        lblName = new javax.swing.JLabel();
        imgPoquemonUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jProgressBar1.setForeground(new java.awt.Color(102, 255, 102));
        jProgressBar1.setMaximum(10);
        jProgressBar1.setValue(10);

        jProgressBar2.setForeground(new java.awt.Color(102, 255, 102));
        jProgressBar2.setMaximum(10);
        jProgressBar2.setValue(10);

        lblName.setText("xxx");

        imgPoquemonUser.setText("xxx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgPoquemonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblName)
                .addGap(53, 53, 53)
                .addComponent(imgPoquemonUser, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgPoquemonUser;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
